<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261007123000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add isolated temporary creation-origin events for team creation limits';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE team_creation_origin_event (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, signal_type VARCHAR(8) NOT NULL, signal_digest CHAR(64) NOT NULL, created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL, PRIMARY KEY(id), CONSTRAINT team_creation_origin_type CHECK (signal_type IN ('ip', 'device'))) ");
        $this->addSql('CREATE INDEX team_creation_origin_lookup_idx ON team_creation_origin_event (signal_type, signal_digest, created_at)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE team_creation_origin_event');
    }
}
